name: Vitest Workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest


    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'

    
    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm exec vitest run --reporter=junit --outputFile=results/report.xml
    - name: Print directory contents
      run: ls -R /workspaces/sveltekit-boi

    - name: Create and upload test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Vitest Tests
        path: results/report.xml
        reporter: jest-junit

      
    # - name: Check exit code
    #   if: ${{ failure() }}
    #   run: exit 1